// AUTO-GENERATED by scripts/sync-tests.sh — DO NOT EDIT (source: crates/lbm-core/tests/smoke_poiseuille.rs)
//! Smoke test: body-force-driven Poiseuille flow between half-way
//! bounce-back walls. TRT with magic 3/16 must reproduce the discrete
//! parabola exactly; BGK converges at 2nd order.

mod common;
use common::run_to_steady;

use lbm_core2::compat::prelude::*;

/// Returns (simulated profile, analytical profile) over the fluid rows.
fn poiseuille(ny: usize, collision: Collision) -> (Vec<f64>, Vec<f64>) {
    let nu = 0.1;
    let g = 1e-6;
    let mut sim: Simulation<f64> = SimConfig {
        nx: 4,
        ny,
        nu,
        collision,
        edges: Edges {
            left: EdgeBC::Periodic,
            right: EdgeBC::Periodic,
            bottom: EdgeBC::BounceBack,
            top: EdgeBC::BounceBack,
        },
        force: [g, 0.0],
        ..Default::default()
    }
    .build()
    .unwrap();
    // Tolerance 1e-11: BGK sits in a round-off plateau at ~1e-12 relative
    // (measured; see docs/PHYSICS.md), it never reaches 1e-13.
    assert!(
        run_to_steady(&mut sim, 500, 1e-11, 200_000),
        "did not reach steady state"
    );
    let h = (ny - 2) as f64;
    let mut simulated = Vec::new();
    let mut analytic = Vec::new();
    for j in 1..=(ny - 2) {
        let yw = j as f64 - 0.5;
        simulated.push(sim.ux(0, j));
        analytic.push(g / (2.0 * nu) * yw * (h - yw));
    }
    (simulated, analytic)
}

fn linf_rel(sim: &[f64], reference: &[f64]) -> f64 {
    let umax = reference.iter().cloned().fold(0.0f64, f64::max);
    sim.iter()
        .zip(reference)
        .map(|(s, r)| (s - r).abs())
        .fold(0.0f64, f64::max)
        / umax
}

#[test]
fn trt_magic_is_exact() {
    let (sim, exact) = poiseuille(10, Collision::default());
    let err = linf_rel(&sim, &exact);
    assert!(err < 1e-10, "Linf_rel = {err:e}, profile = {sim:?}");
}

#[test]
fn profile_is_symmetric() {
    let (sim, _) = poiseuille(10, Collision::default());
    let umax = sim.iter().cloned().fold(0.0f64, f64::max);
    let h = sim.len();
    for j in 0..h / 2 {
        let d = (sim[j] - sim[h - 1 - j]).abs();
        assert!(
            d < 1e-12 * umax,
            "asymmetry at row {j}: {d:e} (umax {umax:e})"
        );
    }
}

#[test]
fn bgk_is_second_order() {
    let (s8, a8) = poiseuille(10, Collision::Bgk);
    let (s16, a16) = poiseuille(18, Collision::Bgk);
    let e8 = linf_rel(&s8, &a8);
    let e16 = linf_rel(&s16, &a16);
    let order = (e8 / e16).log2();
    assert!(order > 1.7, "order = {order} (e8 = {e8:e}, e16 = {e16:e})");
}
