#!/usr/bin/env bash
# Sync the V1 (crates/lbm-core) integration test suite into lbm-core2,
# retargeting it at the compat facade. Mechanical only — never edit the
# generated files by hand (rerun this script instead; drift prevention).
#
# Substitution: `lbm_core` -> `lbm_core2::compat` (module tree is mirrored
# 1:1, so paths like lbm_core::prelude / ::lattice / ::multiphase all map).
#
# Generated files carry a marker header; the script deletes previously
# generated files (by marker) before regenerating, so removals in V1
# propagate too.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/crates/lbm-core/tests"
DST="$ROOT/crates/lbm-core2/tests"
MARKER="AUTO-GENERATED by scripts/sync-tests.sh"

[ -d "$SRC" ] || { echo "V1 test dir not found: $SRC" >&2; exit 1; }
mkdir -p "$DST"

# Remove previously generated files (identified by marker header).
find "$DST" -name '*.rs' -print0 | while IFS= read -r -d '' f; do
    if head -n 1 "$f" | grep -q "$MARKER"; then
        rm "$f"
    fi
done
if [ -d "$DST/common" ] && [ -f "$DST/common/mod.rs" ] \
    && head -n 1 "$DST/common/mod.rs" | grep -q "$MARKER"; then
    rm -r "$DST/common"
fi

# Copy + retarget.
count=0
while IFS= read -r -d '' src; do
    rel="${src#"$SRC"/}"
    dst="$DST/$rel"
    mkdir -p "$(dirname "$dst")"
    {
        echo "// $MARKER — DO NOT EDIT (source: crates/lbm-core/tests/$rel)"
        # perl, not sed: BSD sed has no \b word boundary and silently copies
        # the file unmodified (which left the "synced" suite running on V1).
        perl -pe 's/\blbm_core\b/lbm_core2::compat/g' "$src"
    } > "$dst"
    count=$((count + 1))
done < <(find "$SRC" -name '*.rs' -print0)

echo "synced $count test file(s) from lbm-core to lbm-core2 (compat)"
