/**
 * Scenario JSON (v0) export for Agent mode.
 *
 * The format must match `Scenario` in `crates/lbm-scenario/src/lib.rs` (serde
 * camelCase, deny_unknown_fields). JSON exported here can be run as-is via
 * `lbm run scenario.json`.
 */

import type { EdgeBC, Engine, EngineConfig } from "./engine/types.ts";

/** Rust: `Obstacle::Rect` (closed interval including both endpoints, lattice coordinates; y=0 is the bottom edge) */
export interface RectObstacle {
  shape: "rect";
  x0: number;
  y0: number;
  x1: number;
  y1: number;
}

export interface ScenarioInitRest {
  kind: "rest";
}

export interface ScenarioInitDroplet {
  kind: "droplet";
  cx: number;
  cy: number;
  r: number;
  rhoLiquid: number;
  rhoVapor: number;
}

export type ScenarioField = "speed" | "ux" | "uy" | "rho" | "vorticity";

export interface ScenarioOutput {
  field: ScenarioField;
  format: "png" | "csv";
  /** Snapshot every N steps (0 = only at the end) */
  every: number;
}

/** Rust: `Scenario` (camelCase). Do not include optional fields when absent */
export interface Scenario {
  version: number;
  name: string;
  grid: { nx: number; ny: number };
  physics: {
    nu: number;
    collision: { type: "bgk" | "trt" };
    force: [number, number];
    precision: "f32" | "f64";
  };
  edges: { left: EdgeBC; right: EdgeBC; bottom: EdgeBC; top: EdgeBC };
  obstacles?: RectObstacle[];
  init: ScenarioInitRest | ScenarioInitDroplet;
  multiphase?: { g: number; gWall: number };
  run: { steps: number };
  outputs: ScenarioOutput[];
}

/**
 * Decompose the solid mask into a set of non-overlapping rectangles (greedy
 * algorithm). From each found cell, extend the rectangle first to the right
 * (+x), then upward (+y). Rectangles use the closed interval [x0..x1] ×
 * [y0..y1], matching the Rust side; their union matches the mask exactly
 * (a lossless decomposition, not an approximation).
 */
export function maskToRects(mask: Uint8Array, nx: number, ny: number): RectObstacle[] {
  const covered = new Uint8Array(nx * ny);
  const rects: RectObstacle[] = [];

  for (let y = 0; y < ny; y++) {
    const row = y * nx;
    for (let x = 0; x < nx; x++) {
      if (mask[row + x] !== 1 || covered[row + x] === 1) continue;

      // Extend to the right
      let x1 = x;
      while (x1 + 1 < nx && mask[row + x1 + 1] === 1 && covered[row + x1 + 1] === 0) {
        x1++;
      }

      // Extend upward (while the whole row [x..x1] is solid and uncovered)
      let y1 = y;
      grow: while (y1 + 1 < ny) {
        const next = (y1 + 1) * nx;
        for (let xx = x; xx <= x1; xx++) {
          if (mask[next + xx] !== 1 || covered[next + xx] === 1) break grow;
        }
        y1++;
      }

      for (let yy = y; yy <= y1; yy++) {
        const r = yy * nx;
        for (let xx = x; xx <= x1; xx++) covered[r + xx] = 1;
      }
      rects.push({ shape: "rect", x0: x, y0: y, x1, y1 });
    }
  }
  return rects;
}

/**
 * Assemble a scenario JSON from the current engine state + UI config.
 * Obstacles are extracted from the current solid mask via rectangle
 * decomposition.
 *
 * Note: wall-type edges (bounceBack / movingWall) are realized by lbm-core as
 * a 1-cell solid rim around the perimeter, so the engine's mask includes the
 * perimeter cells. This rim is regenerated by `lbm run` from the edges spec
 * (and overwriting movingWall with an obstacle would kill the driven wall
 * anyway), so only the interior cells the user can actually paint are
 * exported (painting is not allowed on the 1-cell perimeter, by design).
 */
export function buildScenario(engine: Engine, cfg: EngineConfig, name: string): Scenario {
  const { nx, ny } = engine;
  const mask = engine.solidMask();
  const interior = new Uint8Array(nx * ny);
  for (let y = 1; y < ny - 1; y++) {
    const row = y * nx;
    for (let x = 1; x < nx - 1; x++) {
      interior[row + x] = mask[row + x]!;
    }
  }
  const obstacles = maskToRects(interior, nx, ny);

  return {
    version: 0,
    name,
    grid: { nx: engine.nx, ny: engine.ny },
    physics: {
      nu: cfg.nu,
      collision: { type: cfg.collision },
      force: [cfg.force[0], cfg.force[1]],
      precision: "f64",
    },
    edges: {
      left: cfg.edges.left,
      right: cfg.edges.right,
      bottom: cfg.edges.bottom,
      top: cfg.edges.top,
    },
    ...(obstacles.length > 0 ? { obstacles } : {}),
    init: cfg.init
      ? {
          kind: "droplet",
          cx: cfg.init.cx,
          cy: cfg.init.cy,
          r: cfg.init.r,
          rhoLiquid: cfg.init.rhoLiquid,
          rhoVapor: cfg.init.rhoVapor,
        }
      : { kind: "rest" },
    ...(cfg.multiphase
      ? { multiphase: { g: cfg.multiphase.g, gWall: cfg.multiphase.gWall ?? 0 } }
      : {}),
    run: { steps: 20000 },
    outputs: [{ field: cfg.multiphase ? "rho" : "speed", format: "png", every: 0 }],
  };
}
